# Generated by Django 3.0.6 on 2020-06-15 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='firewallstatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=30)),
                ('Service_Name', models.CharField(max_length=50)),
                ('Display_Name', models.CharField(max_length=50)),
                ('Status', models.CharField(max_length=20)),
            ],
        ),
    ]
